### ISSUE TITLE
TypeError: Object

### ISSUE THREAD

**Issue by mrbrdo** [maccman/juggernaut#1]
Hello,

I followed the readme to install all the dependencies as you instruct. After I run node server.js i get:

node.js:63
    throw e;
    ^
TypeError: Object

Nothing more. Just before it errors out it seems it connects to the redis server (it gets a connection but then it is immediately closed). I installed node from the git repo, everything else like you specified in the readme. Also tried all versions of redis server (upto 2.0.1).

**Comment by mrbrdo** [comment]
The error seems to come from lib/juggernaut/publish.js line 10:
  this.client.subscribeTo("juggernaut", function(_, data) {
    sys.log("Received: " + data);

```
Channel.publish(Message.fromJSON(data));
```

  });

If I comment this out, I don't get the error. Hope it helps.

**Comment by maccman** [comment]
Somebody else had the same problem. It's actually a UTF8 problem with Node. Using this branch of Node should fix it:

http://github.com/ry/node/tree/v0.2

**Comment by mrbrdo** [comment]
You are correct, it works with this version. Thank you.

**Comment by datapimp** [comment]
It works for me as well.

But now I'm running into another error with redis-client:

TypeError: Cannot read property 'length' of undefined

/usr/local/lib/node/.npm/redis-client/0.3.5/package/lib/redis-client.js:394
    var callback = originalCommand[originalCommand.length - 1];

**Comment by mferrier** [comment]
+1 to "cannot read property length of undefined" issue

**Comment by maccman** [comment]
mferrier - this is an error with the latest node. I'm looking into it.

**Comment by mferrier** [comment]
cool, thanks for the quick feedback.

**Comment by welaika** [comment]
are there any news on the "cannot read property length of undefined" thing?

**Comment by maccman** [comment]
Yes, fixed. Follow the new Juggernaut readme.

**Comment by PanosJee** [comment]
I am using Redis 2.0.2, latest juggernaut and Node 0.2.4 but still have this error.

**Comment by maccman** [comment]
Really? I'm afraid I can't reproduce it. You get no stack trace?

**Comment by PanosJee** [comment]
Hi Alex, that s quick response!
The full stack trace is:

29 Oct 16:29:48 - socket.io ready - accepting connections

/Users/panosjee/.node_libraries/.npm/redis-client/0.3.5/package/lib/redis-client.js:394
    var callback = originalCommand[originalCommand.length - 1];
                                                  ^
TypeError: Cannot read property 'length' of undefined
    at Client.onReply_ (/Users/panosjee/.node_libraries/.npm/redis-client/0.3.5/package/lib/redis-client.js:394:51)
    at /Users/panosjee/.node_libraries/.npm/redis-client/0.3.5/package/lib/redis-client.js:136:34
    at ReplyParser.feed (/Users/panosjee/.node_libraries/.npm/redis-client/0.3.5/package/lib/redis-client.js:169:21)
    at Stream.<anonymous> (/Users/panosjee/.node_libraries/.npm/redis-client/0.3.5/package/lib/redis-client.js:337:28)
    at Stream.emit (events:27:15)
    at IOWatcher.callback (net:489:16)
    at node.js:772:9

Btw the redis-clients is the one of technoweenie

Thanx a lot!

**Comment by maccman** [comment]
ah ok - you need to use the redis client I've fixed. Follow the Juggernaut readme.

**Comment by PanosJee** [comment]
Thanx awesome, it works like a charm! I think the Readme does not include your fork of redis client. You only refer to:
node.js requirements:
- socket.io
- node-static
- redis-client

**Comment by maccman** [comment]
Yes, that bit of the readme needs to be updated - the requirements are vendorized now.

**Comment by licx** [comment]
How can I get the updated version of the redis client? I have node 0.2.4 (juggernaut doesn't seem to work with node 3 unstable) and redis server 2.0.3. I still get this error:

TypeError: Cannot read property 'length' of undefined

**Comment by PanosJee** [comment]
http://github.com/maccman/redis-node-client

**Comment by leepa** [comment]
I have tried the maccman/redis-node-client and I just get hangs instead of the error.

**Comment by mferrier** [comment]
thanks for the fix. works great for me.

for anyone who checked this out before the requirements were vendorized, you try blowing away your juggernaut repo and reclone with --recursive
